# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombramientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('codigo_centro', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(blank=True, max_length=120, null=True)),
                ('direccion_postal', models.CharField(blank=True, max_length=120, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=6, null=True)),
                ('tlf', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=140, null=True)),
                ('web', models.CharField(blank=True, max_length=140, null=True)),
                ('naturaleza', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_centro', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'centros_region',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigo_especialidad', models.TextField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idioma', models.TextField(blank=True, null=True)),
                ('tiempo_parcial', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('nombre_provincia', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('minutos', models.FloatField(blank=True, null=True)),
                ('sumario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.AlterModelOptions(
            name='correspondencias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gaseosa',
            options={'ordering': ['apellido_1', 'apellido_2']},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nombramiento',
            options={},
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_destino', to='nombramientos.Localidad'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_origen', to='nombramientos.Localidad'),
        ),
        migrations.AddField(
            model_name='centro',
            name='codigo_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nombramientos.Localidad'),
        ),
    ]
