# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombramientos', '0002_auto_20160824_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='nombre_provincia',
        ),
        migrations.RemoveField(
            model_name='nombramiento',
            name='id',
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nombramientos.Provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nombramiento',
            name='codigo_centro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nombramientos.Centro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='auxiliar',
            field=models.TextField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='especialidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nombramientos.Especialidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='fecha_fin',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='fecha_inicio',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='nif',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='nombre_completo',
            field=models.TextField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='procedimiento',
            field=models.TextField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='correspondencias',
            unique_together=set([('codigo_gaseosa', 'codigo_real')]),
        ),
    ]
